# Nixpacks configuration for ChatOS
# This ensures Node.js and npm are available in the build environment

[providers]
node = "18"  # Use Node.js 18 (matches your project requirements)

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.build]
cmds = ["npm ci", "npm run build"]

[phases.start]
cmd = "npm run preview"

[variables]
NODE_ENV = "production"